A/A/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.user_login,name = 'user_login'),
    path('register/',views.user_register,name='user_register'),
    path('logout/',views.user_logout, name = 'user_logout'),
]

A/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.all_articles , name='all_articles'),
    path('<int:id>/<slug:slug>' , views.article_detail , name = 'article_detail')
]

A/accounts/models.py
from django.db import models

# Create your models here.

A/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class PublishArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = 'publish')

class Article(models.Model):
    STATUS = (
        ('draft','Draft'),
        ('publish','Publish')
    )

    writer = models.ForeignKey(User,on_delete= models.CASCADE)
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150 ,unique=True,allow_unicode=True)
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20,choices=STATUS,default='draft')
    objects = models.Manager()
    published = PublishArticleManager()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:article_detail", args=[self.id,self.slug])
    

A/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=30, required=True,widget=forms.TextInput(
        attrs={'class':'form-control','placeholder':'Your Username'}))

    password = forms.CharField(max_length=30, required=True,widget=forms.PasswordInput(
        attrs={'class':'form-control','placeholder':'Your Password'}))


class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=30, required=True,widget=forms.TextInput(
        attrs={'class':'form-control','placeholder':'Your Username'}))

    email = forms.EmailField(max_length=50,widget=forms.EmailInput(
        attrs={'class':'form-control','placeholder':'Your Email'}))

    password = forms.CharField(label='Password', max_length=30, required=True,widget=forms.PasswordInput(
        attrs={'class':'form-control','placeholder':'Your Password'}))

    repassword = forms.CharField(label='Repassword', max_length=30, required=True,widget=forms.PasswordInput(
        attrs={'class':'form-control','placeholder':'Your Repassword'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError('email already exists')
        return email

    # def clean_repassword(self):
    #     pass1 = self.cleaned_data['password']
    #     repass = self.cleaned_data['repassword']
    #     if pass1 != repass:
    #         raise forms.ValidationError('passwoed not match repassword')
    #     return pass1

    def clean(self):
        cleaned_data = super().clean()
        pass1 = cleaned_data.get('password')
        pass2 = cleaned_data.get('repassword')
        if pass1 and pass2:
            if pass1 != pass2:
                raise forms.ValidationError('passwoed not match repassword')

A/accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, login , logout
from .forms import UserLoginForm,UserRegisterForm
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request,'you login successfully','success')
                return redirect('blog:all_articles')
            else:
                messages.error(request,'wrong username or password','danger')
    else:
        form = UserLoginForm()
    return render(request,'accounts/login.html',{'form':form})


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password'])
            messages.success(request,'you register successfully','success')
            return redirect('accounts:user_login')
    else:
        form = UserRegisterForm()
    return render(request,'accounts/register.html',{'form':form})


def user_logout(request):
    logout(request)
    messages.success(request,'you are log out')
    return redirect('blog:all_articles')

A/blog/views.py
from django.shortcuts import render ,get_object_or_404
from .models import Article

# Create your views here.
def all_articles(request):
    #all_articles = Article.objects.filter(status='publish')
    all_articles = Article.published.all()
    return render(request,'blog/all_articles.html',{'all_articles':all_articles})

def article_detail(request,id,slug):
    #article = Article.objects.get(id = id,slug = slug)
    article = get_object_or_404(Article , id = id , slug = slug)
    return render(request,'blog/article_detail.html',{'article':article})

A/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
{% endblock %}

A/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
{% endblock %}

A/blog/templates/blog/all_articles.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    {% if all_articles %}
    {% for article in all_articles %}
        <div class="col-6">
            <a href="{{article.get_absolute_url}}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{article.title}}</h5>
                        <p class="card-text">{{article.body|safe}}</p>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
    {% else %}
        <h5>Ooooops! There Is No Article</h5>
    {% endif %}
</div>

{% endblock %}

A/blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'blog/style/style.css' %}">
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{article.title}}</h5>
                <small class="card-text">{{article.created}}</small>
                <small class="card-text">{{article.writer}}</small>
                <p class="card-text">{{article.body|safe}}</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

A/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>
<body>
    <div class="container">
        {% include 'inc/navbar.html' %}
        {% include 'inc/messages.html' %}
        <div class="jumbotron">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

A/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

A/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:all_articles' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}">Login<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_register' %}">Register<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>